cors:
  originPatterns: http://localhost:8080,https://rosivancardoso.com.br,http://localhost:3000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_rosivan?useTimezone=true&serverTimezone=UTC
    username: root
    password: cosmo123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-slq: false
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true

